# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c5100f2709e1f4db5fbee69e59acf368a55f91b661499c45ef5a6b7b5903f0d6d3ca1cb66f738ebb9ce61fd31529375d9f1a3334868154c3357bbcddd11893f

test:
  secret_key_base: cc668bb2a9756047984ba15b80533217b00bcca44e56dadac3b0abc8e54c8a0ec713f4096ec852d6dbe5feece290bc5894d060600a58fc513ef7f26acd6ec966

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
